name: 'Bump Github Tag To New Version'
description: 'Bumps the latest github tag to specified version'
inputs:
  token:
    description: 'Token used for authentication of the repository to update tag'
    required: true
  default-bump:
    description: 'Sets the default tag bump patch, minor, or major'
    required: false
    default: 'patch'
  with-v: 
    description: 'Add v to tag version'
    required: false
  
outputs:
  new-tag: 
    description: 'Newly created tag'
runs:
  using: 'node16'
  main: 'dist/index.js'